fix: only emit Option import when there are optional types
musicglue/joi-ts-generator pull request #7
Opened 2017-07-11 17:38 UTC by nikcorg

2017-07-11 18:40 UTC, leemhenson requested changes
Neat!

2017-07-11 18:40 UTC, leemhenson commented on src/writers/utils.ts
> +  isInterface(t.class) && t.class.fields.some(isOptionalField);
Can these two go into `predicates.ts` instead with all the other `(t: T) => boolean`s?

Also, the naming here isn't quite perfect: `s/isOptionalType/hasOptionalFields/` would be a smidge better.

2017-07-12 08:28 UTC, nikcorg commented on src/writers/utils.ts
> +  isInterface(t.class) && t.class.fields.some(isOptionalField);
Addressed.

2017-07-12 09:24 UTC, leemhenson approved these changes

2017-07-12 09:24 UTC, merged